KurumsalWeb/Models/Features.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Features
    {
        public int FeatureId { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string LogoURL { get; set; }
        public string Name { get; set; }
    }
}

KurumsalWeb/Controllers/FeaturesController.cs
using KurumsalWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace KurumsalWeb.Controllers
{
    public class FeaturesController : Controller
    {
        // GET: Features
        KurumsalDBEntities db = new KurumsalDBEntities();
        public ActionResult Index()
        {
            var query = db.Features.ToList();
            return View(query);
        }

        // GET: Features/Edit/5
        public ActionResult Edit(int id)
        {
            var feature = db.Features.Where(x => x.FeatureId == id).SingleOrDefault();
            return View(feature);
        }

        // POST: Features/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(int id, Features features ,HttpPostedFileBase LogoURL)
        {
            if (ModelState.IsValid)
            {
                var feature = db.Features.Where(x => x.FeatureId == id).SingleOrDefault();

                if (LogoURL != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(feature.LogoURL)))
                    {
                        System.IO.File.Delete(Server.MapPath(feature.LogoURL));
                    }
                    WebImage img = new WebImage(LogoURL.InputStream);
                    FileInfo imginfo = new FileInfo(LogoURL.FileName);

                    string logoname = LogoURL.FileName + imginfo.Extension;
                    img.Resize(200, 200);
                    img.Save("~/Uploads/Features/"+ logoname);

                    feature.LogoURL = "/Uploads/Features/" + logoname;
                }
                feature.Title = features.Title;
                feature.Keywords = features.Keywords;
                feature.Description = features.Description;
                feature.Name = features.Name;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(features);
        }
    }
}

KurumsalWeb/Views/Features/Edit.cshtml
@model KurumsalWeb.Models.Features

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout .cshtml";
}

<script type="text/javascript">
    CKEDITOR.replace("editor")

</script>

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Features", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Features</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FeatureId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Keywords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="Description" class="ckeditor">@Model.Description</textarea>
              
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogoURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="LogoURL" accept=".png,.jpg,.jpeg" class="form-control"/>
                @Html.ValidationMessageFor(model => model.LogoURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KurumsalWeb/Views/Features/Index.cshtml
@model IEnumerable<KurumsalWeb.Models.Features>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout .cshtml";
}



<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-striped table-responsive-sm">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Keywords)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogoURL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Transactions
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Keywords)
        </td>
        <td>
            @Html.Raw(item.Description)
        </td>
        <td>
           <img class="img-responsive" src="@item.LogoURL" width="200"height="200"></img>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.FeatureId }) 
           
        </td>
    </tr>
}

</table>